(cl:defpackage assignment_2_2023-msg
  (:use )
  (:export
   "<INTERFACE>"
   "INTERFACE"
   "<PLANNINGACTION>"
   "PLANNINGACTION"
   "<PLANNINGACTIONFEEDBACK>"
   "PLANNINGACTIONFEEDBACK"
   "<PLANNINGACTIONGOAL>"
   "PLANNINGACTIONGOAL"
   "<PLANNINGACTIONRESULT>"
   "PLANNINGACTIONRESULT"
   "<PLANNINGFEEDBACK>"
   "PLANNINGFEEDBACK"
   "<PLANNINGGOAL>"
   "PLANNINGGOAL"
   "<PLANNINGRESULT>"
   "PLANNINGRESULT"
   "<ROBOTINFO>"
   "ROBOTINFO"
  ))

