// Generated by gencpp from file assignment_2_2023/GetCoordinates.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_GETCOORDINATES_H
#define ASSIGNMENT_2_2023_MESSAGE_GETCOORDINATES_H

#include <ros/service_traits.h>


#include <assignment_2_2023/GetCoordinatesRequest.h>
#include <assignment_2_2023/GetCoordinatesResponse.h>


namespace assignment_2_2023
{

struct GetCoordinates
{

typedef GetCoordinatesRequest Request;
typedef GetCoordinatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoordinates
} // namespace assignment_2_2023


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2023::GetCoordinates > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::assignment_2_2023::GetCoordinates&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2023::GetCoordinates > {
  static const char* value()
  {
    return "assignment_2_2023/GetCoordinates";
  }

  static const char* value(const ::assignment_2_2023::GetCoordinates&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2023::GetCoordinatesRequest> should match
// service_traits::MD5Sum< ::assignment_2_2023::GetCoordinates >
template<>
struct MD5Sum< ::assignment_2_2023::GetCoordinatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::GetCoordinates >::value();
  }
  static const char* value(const ::assignment_2_2023::GetCoordinatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::GetCoordinatesRequest> should match
// service_traits::DataType< ::assignment_2_2023::GetCoordinates >
template<>
struct DataType< ::assignment_2_2023::GetCoordinatesRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::GetCoordinates >::value();
  }
  static const char* value(const ::assignment_2_2023::GetCoordinatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2023::GetCoordinatesResponse> should match
// service_traits::MD5Sum< ::assignment_2_2023::GetCoordinates >
template<>
struct MD5Sum< ::assignment_2_2023::GetCoordinatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::GetCoordinates >::value();
  }
  static const char* value(const ::assignment_2_2023::GetCoordinatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::GetCoordinatesResponse> should match
// service_traits::DataType< ::assignment_2_2023::GetCoordinates >
template<>
struct DataType< ::assignment_2_2023::GetCoordinatesResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::GetCoordinates >::value();
  }
  static const char* value(const ::assignment_2_2023::GetCoordinatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_GETCOORDINATES_H
