// Generated by gencpp from file assignment_2_2023/robotInfoSrv.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRV_H
#define ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRV_H

#include <ros/service_traits.h>


#include <assignment_2_2023/robotInfoSrvRequest.h>
#include <assignment_2_2023/robotInfoSrvResponse.h>


namespace assignment_2_2023
{

struct robotInfoSrv
{

typedef robotInfoSrvRequest Request;
typedef robotInfoSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotInfoSrv
} // namespace assignment_2_2023


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2023::robotInfoSrv > {
  static const char* value()
  {
    return "864975fef3d37f98fc7bae31c8fe41ea";
  }

  static const char* value(const ::assignment_2_2023::robotInfoSrv&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2023::robotInfoSrv > {
  static const char* value()
  {
    return "assignment_2_2023/robotInfoSrv";
  }

  static const char* value(const ::assignment_2_2023::robotInfoSrv&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2023::robotInfoSrvRequest> should match
// service_traits::MD5Sum< ::assignment_2_2023::robotInfoSrv >
template<>
struct MD5Sum< ::assignment_2_2023::robotInfoSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::robotInfoSrv >::value();
  }
  static const char* value(const ::assignment_2_2023::robotInfoSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::robotInfoSrvRequest> should match
// service_traits::DataType< ::assignment_2_2023::robotInfoSrv >
template<>
struct DataType< ::assignment_2_2023::robotInfoSrvRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::robotInfoSrv >::value();
  }
  static const char* value(const ::assignment_2_2023::robotInfoSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2023::robotInfoSrvResponse> should match
// service_traits::MD5Sum< ::assignment_2_2023::robotInfoSrv >
template<>
struct MD5Sum< ::assignment_2_2023::robotInfoSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::robotInfoSrv >::value();
  }
  static const char* value(const ::assignment_2_2023::robotInfoSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::robotInfoSrvResponse> should match
// service_traits::DataType< ::assignment_2_2023::robotInfoSrv >
template<>
struct DataType< ::assignment_2_2023::robotInfoSrvResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::robotInfoSrv >::value();
  }
  static const char* value(const ::assignment_2_2023::robotInfoSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRV_H
