// Generated by gencpp from file assignment_2_2023/robotInfoSrvResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRVRESPONSE_H
#define ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct robotInfoSrvResponse_
{
  typedef robotInfoSrvResponse_<ContainerAllocator> Type;

  robotInfoSrvResponse_()
    : distance(0.0)
    , vel_x(0.0)
    , vel_z(0.0)  {
    }
  robotInfoSrvResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , vel_x(0.0)
    , vel_z(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _vel_x_type;
  _vel_x_type vel_x;

   typedef double _vel_z_type;
  _vel_z_type vel_z;





  typedef boost::shared_ptr< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotInfoSrvResponse_

typedef ::assignment_2_2023::robotInfoSrvResponse_<std::allocator<void> > robotInfoSrvResponse;

typedef boost::shared_ptr< ::assignment_2_2023::robotInfoSrvResponse > robotInfoSrvResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2023::robotInfoSrvResponse const> robotInfoSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.vel_x == rhs.vel_x &&
    lhs.vel_z == rhs.vel_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "864975fef3d37f98fc7bae31c8fe41ea";
  }

  static const char* value(const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x864975fef3d37f98ULL;
  static const uint64_t static_value2 = 0xfc7bae31c8fe41eaULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/robotInfoSrvResponse";
  }

  static const char* value(const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
"float64 vel_x\n"
"float64 vel_z\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.vel_x);
      stream.next(m.vel_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotInfoSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::robotInfoSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "vel_x: ";
    Printer<double>::stream(s, indent + "  ", v.vel_x);
    s << indent << "vel_z: ";
    Printer<double>::stream(s, indent + "  ", v.vel_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_ROBOTINFOSRVRESPONSE_H
