(cl:defpackage assignment_2_2023-srv
  (:use )
  (:export
   "GETCOORDINATES"
   "<GETCOORDINATES-REQUEST>"
   "GETCOORDINATES-REQUEST"
   "<GETCOORDINATES-RESPONSE>"
   "GETCOORDINATES-RESPONSE"
   "ROBOTINFOSRV"
   "<ROBOTINFOSRV-REQUEST>"
   "ROBOTINFOSRV-REQUEST"
   "<ROBOTINFOSRV-RESPONSE>"
   "ROBOTINFOSRV-RESPONSE"
  ))

